### ISSUE TITLE
Remove branch banner for unauthenticated users 

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot-plugin-workflow-dolt#12]
This is pre-login.  Can we ensure the banner isn't displayed without auth?

![image](https://user-images.githubusercontent.com/6332586/121950386-927cc080-cd27-11eb-93cf-a7c7a07e847e.png)

**Comment by andrew-wm-arthur** [comment]
addressed in https://github.com/nautobot/nautobot-plugin-workflow-dolt/commit/6fc9639249e08c0bbc22b31dbf5e13c12f938dd2
