### ISSUE TITLE
Update commit "name"

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot-plugin-workflow-dolt#14]
After doing #13 the name will be different. Would like to change the "name" and what's in the breadcrumb - from hash to the commit message.

![image](https://user-images.githubusercontent.com/6332586/122552087-d9a6d200-d003-11eb-8216-41d32280cc3c.png)

**Comment by andrew-wm-arthur** [comment]
addressed in https://github.com/nautobot/nautobot-plugin-workflow-dolt/commit/f17bafb03c4a002cb261ea05e809b1d40a5433a2
