### ISSUE TITLE
update breadcrumbs

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot-plugin-workflow-dolt#15]
Similar to the URL, we may end up changing it from being `dolt` but for now I'd like to add to the breadcrumbs in Commits.

On the commits page, it's currently:
`Commits / qgea09r8knk5qjvqal1l11c0cp58cqnj`

Let's add to it so it is `Dolt / Commits / $commit-message` (this is adding "Dolt" and swapping out hash for message per #14 

Same would be true for a branch page.  Add "Dolt" to the breadcrumb.

Also for the commits page, instead of just having the page title being "Commits in Active Branch," let's add breadcrumbs:
`Dolt / Branches / $branch-name` with the page name being $branch-name

**Comment by andrew-wm-arthur** [comment]
What would the link be for `Dolt`? There's no top level page for this plugin. Maybe this portion of the breadcrumb doesn't have a link

**Comment by jedelman8** [comment]
Right.  For now that's what I would do.

**Comment by andrew-wm-arthur** [comment]
addressed in https://github.com/nautobot/nautobot-plugin-workflow-dolt/commit/8359bb9931338793b9ea9c73a52f8f8a38d04697
