### ISSUE TITLE
new branch not being displayed branch list

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot-plugin-workflow-dolt#16]
it did eventually show, but wasn't there after a few minutes. see the branch in banner is not in the list.

![image](https://user-images.githubusercontent.com/6332586/122553747-15db3200-d006-11eb-8f99-682402765526.png)

**Comment by andrew-wm-arthur** [comment]
I believe this was a problem with caching, Django Cacheops was enabled
