### ISSUE TITLE
change default ordering of commits table

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot-plugin-workflow-dolt#17]
Change to:
Message | Date | Committer | Email | Commit Hash

It is currently: 
Commit Hash | Committer | Email | Date | Message

**Comment by andrew-wm-arthur** [comment]
addressed in https://github.com/nautobot/nautobot-plugin-workflow-dolt/commit/7c197f1930a6a22984b005a8a1d8ffeba0866f58

**Comment by andrew-wm-arthur** [comment]
Change column name to "Commit Message" from "Short Message"

**Comment by andrew-wm-arthur** [comment]
https://github.com/nautobot/nautobot-plugin-workflow-dolt/commit/992edfccd55f96031f32a1172d62afbf0f88890d
