### ISSUE TITLE
discussion on diffs

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot-plugin-workflow-dolt#18]
After deleting a device, there is a large set of diffs.

![image](https://user-images.githubusercontent.com/6332586/122561044-568b7900-d00f-11eb-9632-44335f2dd426.png)

Is there a reason why the device name is not shown in the interfaces diff?  This would become difficult to digest if there were multiple devices deleted with the same interfaces.

Few things with a focus on understanding and readability:

For the change types, there is currently added, removed, before, and after.  It would be nice to have "changed" in addition to before or after for the only value is displayed in that column.  Here is an example of what it could be:
![image](https://user-images.githubusercontent.com/6332586/122561961-796a5d00-d010-11eb-929c-a114866ae24c.png)

Open to ideas for the visual, but I'd rather be explicit in stating it was a change.

I'd also like to explore adding a thin empty row (or anything else) to differentiate between "changes" since it's two rows per change and it's harder to read when there are many of them. Another idea is numbering them - add an "ID" column? Again the goal is to make the visual clean and understandable especially when the diff set is more than a few lines.

It would still be great to highlight the exact column of changed data when it is of type "change".

**Comment by andrew-wm-arthur** [comment]
Highlighting the changed fields in the before/after diff would add a lot of clarity to the view. I started to add it and it was surprisingly complex to render it with the table view library. It's definitely needed

**Comment by itdependsnetworks** [comment]
Can we capture the repr of the entry?
