### ISSUE TITLE
Pull Request Home Screen Needs `Add` button

### ISSUE THREAD

**Issue by tim-fiola** [nautobot/nautobot-plugin-workflow-dolt#31]
The Pull Request Home Screen does not have a button to Add/Create a pull request, forcing the user to go to Dolt-->Pull Requests-->+ button to create one

![image](https://user-images.githubusercontent.com/13647153/130699290-b53b0ca3-75cf-4a2b-b775-8d40c7b4fd87.png)

**Comment by itdependsnetworks** [comment]
Can you try the same from master branch? It may or may not result differently

**Comment by tim-fiola** [comment]
It is not there when `master` is active either.


![image](https://user-images.githubusercontent.com/13647153/130710459-4e219d89-9803-4883-bafc-557e36079be9.png)

**Comment by andrew-wm-arthur** [comment]
addressed in https://github.com/nautobot/nautobot-plugin-workflow-dolt/commit/2817f96c6c1c5e4ab55ea6b9ef82a56ee418dd3a
