### ISSUE TITLE
Center text in "Active Branch" banner

### ISSUE THREAD

**Issue by andrew-wm-arthur** [nautobot/nautobot-plugin-workflow-dolt#5]
![image](https://user-images.githubusercontent.com/8837413/120693448-ddf8ba00-c45d-11eb-8672-557891b85779.png)

**Comment by jedelman8** [comment]
It's center text vertically and horizontally.  I'd also align the text type/size to what's normally in the banner within Nautobot.

**Comment by andrew-wm-arthur** [comment]
centered in : https://github.com/nautobot/nautobot-plugin-workflow-dolt/commit/22972a08a7d9c41293e84c14319d59c7cdfe5a5e

**Comment by jedelman8** [comment]
I see it centered horizontally, but it doesn't seem centered vertically. The font still looks off too.  
Login to demo.nautobot.com.  You'll see what I mean.

**Comment by andrew-wm-arthur** [comment]
formatting updated in https://github.com/nautobot/nautobot-plugin-workflow-dolt/commit/1d2e829ae4df4e419293a34f1b1da101b2e861f5

**Comment by jedelman8** [comment]
Thanks.  One more thing I forgot to mention.  Can you capitalize Active Branch - the "A" and "B" ?

**Comment by andrew-wm-arthur** [comment]
addressed in https://github.com/nautobot/nautobot-plugin-workflow-dolt/commit/88ee04c77c1bb55af2bd23fb30319db3e6271a45
