### ISSUE TITLE
Right justify Diff Summary Table

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot-plugin-workflow-dolt#7]
Referencing the following table, let's right justify the counters and try and enter them vertically inline with the text to the left.

![image](https://user-images.githubusercontent.com/6332586/120802974-0988ac80-c511-11eb-8ae8-316a5326f7d3.png)

**Comment by andrew-wm-arthur** [comment]
addressed in https://github.com/nautobot/nautobot-plugin-workflow-dolt/commit/a0e04a1b83108622ef61353b465a90afa78e975f
