### ISSUE TITLE
Change underscore to hyphen in Dolt URLs and APIs

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot-plugin-workflow-dolt#8]
For now, let's `nautobot_dolt` to `nautobot-url` in URLs and APIs

![image](https://user-images.githubusercontent.com/6332586/120810231-d6e2b200-c518-11eb-97af-6bbba64b4600.png)

I don't know if we end up keeping this as the final name, but will be thinking about it, and open to feedback.  Right now, still thinking something more like "Workflow Management" or "Change Management."

**Comment by dgarros** [comment]
For the url we usually remove `nautobot` altogether, it's important to have a prefix for the python namespace to avoid conflict but for the url just `dolt` should be fine. `/plugins/dolt/branches/`

**Comment by andrew-wm-arthur** [comment]
addressed in https://github.com/nautobot/nautobot-plugin-workflow-dolt/commit/9519bbf8abb5ec291a4de05e252b221c38007428
