### ISSUE TITLE
use capital letters in buttons

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot-plugin-workflow-dolt#9]
Let's convert the buttons to use Capital Letters.

![image](https://user-images.githubusercontent.com/6332586/121079107-bda36500-c7a7-11eb-9e85-cb8b982b3913.png)

**Comment by andrew-wm-arthur** [comment]
addressed in https://github.com/nautobot/nautobot-plugin-workflow-dolt/commit/d4e94e7ee565415066aac0b176ded5a4cc2845bb
